name: gql_phoenix_link
description: A graphql link using phoenix sockets
version: 0.1.0
homepage: https://github.com/knaeckeKami/gql_phoenix_link

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  phoenix_socket: ^0.5.0
  gql_exec: ^0.3.0-nullsafety.2
  gql_link: ^0.4.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.15.4
